### ISSUE TITLE
Automation of requirements

### ISSUE THREAD

**Issue by PinkPantherX** [siddhant385/pyhackthon#1]
Hi, I would really like to test your tool. 
Is there any way you could automate the installation of all requirements.
It's hard to find all modules and requirements on google..

**Comment by siddhant385** [comment]
Hey I will create requirements.txt file for the installation of modules But I'm currently busy doing something else. Although you can install all modules as only modules requirement for startup are required to install else all are available with python.
There are only two module required
```
Created requirements.txt
```
Above are the commands for installing modules

**Comment by siddhant385** [comment]
created requirements.txt
